### ISSUE TITLE
Multiempresas

### ISSUE THREAD

**Issue by juliancabcanul** [AndresRamos/ARSoftware.ManejadorDocumentosCfdi#4]
Tengo dado de alta dos empresas en la aplicación, y note que cuando se actualiza la segunda solo toma como default la primera, sobreescribiendo la información correcta.

**Comment by AndresRamos** [comment]
Había un error donde la aplicación estaba sobrescribiendo la configuración de la primera empresa.
En la version 3.1.0 se corrige esto y ya se guarda la configuración de la empresa correspondiente.

**Comment by juliancabcanul** [comment]
Excelente, validamos, saludos y gracias.

 



 

De: Andres Ramos ***@***.***> 
Enviado el: miércoles, 15 de marzo de 2023 04:55 p. m.
Para: AndresRamos/ARSoftware.ManejadorDocumentosCfdi ***@***.***>
CC: Julian Cab Canul ***@***.***>; Author ***@***.***>
Asunto: Re: [AndresRamos/ARSoftware.ManejadorDocumentosCfdi] Multiempresas (Issue #4)

 

Había un error donde la aplicación estaba sobrescribiendo la configuración de la primera empresa.
En la version 3.1.0 se corrige esto y ya se guarda la configuración de la empresa correspondiente.
